export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_FAIL = "ADD_EMPLOYEE_FAIL";

export const GET_SINGLE_EMPLOYEE = "GET_SINGLE_EMPLOYEE";
export const GET_SINGLE_EMPLOYEE_SUCCESS = "GET_SINGLE_EMPLOYEE_SUCCESS";
export const GET_SINGLE_EMPLOYEE_FAIL = "GET_SINGLE_EMPLOYEE_FAIL";

export const GET_EMPLOYEES_LIST = "GET_EMPLOYEES_LIST";
export const GET_EMPLOYEES_LIST_SUCCESS = "GET_EMPLOYEES_LIST_SUCCESS";
export const GET_EMPLOYEES_LIST_FAIL = "GET_EMPLOYEES_LIST_FAIL";

export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE";
export const EDIT_EMPLOYEE_SUCCESS = "EDIT_EMPLOYEE_SUCCESS";
export const EDIT_EMPLOYEE_FAIL = "EDIT_EMPLOYEE_FAIL";

export const ADD_EMPLOYEES_LIST = "ADD_EMPLOYEES_LIST";
export const ADD_EMPLOYEES_LIST_SUCCESS = "ADD_EMPLOYEES_LIST_SUCCESS";
export const ADD_EMPLOYEES_LIST_FAIL = "ADD_EMPLOYEES_LIST_FAIL";

export const SET_LOADING = "SET_LOADING";
